version: 1.0.0.{build}
image: Visual Studio 2019
platform:
- Win32
- x64
configuration:
- Release
install:
- cmd: git submodule -q update --init
before_build:
- ps: Invoke-WebRequest "https://downloads.vigem.org/other/nefarius/vpatch/vpatch.exe" -OutFile vpatch.exe
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\%APPVEYOR_PROJECT_NAME%.rc" --resource.file-version --resource.product-version
build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
artifacts:
- path: 'bin\**\*.dll'
  name: libsbc
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true
