version: 1.5.{build}.0
image: Visual Studio 2019
platform:
- x86
- x64
configuration:
- Release
install:
- cmd: git submodule -q update --init
before_build:
- ps: Invoke-WebRequest "https://downloads.nefarius.at/other/nefarius/vpatch/vpatch.exe" -OutFile vpatch.exe
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\contrib\%APPVEYOR_PROJECT_NAME%.rc" --resource.file-version --resource.product-version
skip_commits:
  files:
    - assets/*
    - '**/*.md'
build:
  project: $(APPVEYOR_BUILD_FOLDER)\contrib\$(APPVEYOR_PROJECT_NAME).sln
artifacts:
- path: 'bin\**\*.dll'
  name: libsbc
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true
