version: 2.1.{build}.0
image: Visual Studio 2022
platform:
- x86
- x64
- ARM64
configuration:
- Release
install:
- cmd: git submodule -q update --init
before_build:
- cmd: dotnet tool install --global Nefarius.Tools.Vpatch
- cmd: vpatch --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\contrib\%APPVEYOR_PROJECT_NAME%.rc" --resource.file-version --resource.product-version
skip_commits:
  files:
    - assets/*
    - '**/*.md'
build:
  project: $(APPVEYOR_BUILD_FOLDER)\contrib\$(APPVEYOR_PROJECT_NAME).sln
artifacts:
- path: 'bin\**\*.dll'
  name: libsbc
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true
